// Generated by https://quicktype.io

export class Calificacion {
  id?: number;
  fecha?: string;
  hora?: string;
  cliente?: string;
  empleado?: string;
  observacion?: string;
  calificacionEnum?: string;
  aceptaPoliticas? : boolean;
}
